export const TestGrid = [
  [
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
  ],
  [
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
  ],
  [
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
  ],
  [
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
  ],
  [
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
  ],
  [
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
  ],
  [
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
  ],
  [
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
  ],
  [
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
  ],
  [
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
  ],
  [
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
  ],
  [
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
  ],
  [
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
  ],
  [
    { WallType: 9, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 0, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
  ],
  [
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
    { WallType: 9, PowerUp: 0 },
  ],
];
