CREATE TABLE guilds (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    creator_fk_users INTEGER REFERENCES users(id) ON DELETE CASCADE,
    guild_title TEXT NOT NULL,
    guild_description TEXT NOT NULL,
    date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMPG
);